
# This is a basic workflow to trigger workflow in another repository

name: Trigger Workflow In Remote Repository

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "dev/**" ]
  #   paths:
  #     - 'fe/**'
  #     - 'be/**'
  #     - 'others/**'
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - 'fe/**'
  #     - 'be/**'
  #     - 'others/**'

  # # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Infra Repo
      #   uses: actions/checkout@v3

      # - name: Detect changed folders
      #   id: changed
      #   uses: dorny/paths-filter@v3
      #   with:
      #     filters: |
      #       frontend:
      #         - 'fe/**'
      #       backend:
      #         - 'be/**'
      #       others:
      #         - 'others/**'

      - name: Workflow Dispatch
        run: |
          curl -X POST https://api.github.com/repos/Dat-Nguyen-Org/MyProject/dispatches \
          -H "Authorization: token ${{ secrets.PAT_REMOTE_TRIGGER }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{
                "event_type": "ci",
                "client_payload": {
                  "content": "Hello World"
                }
              }'
          # gh api \
          # --method POST \
          # -H "Accept: application/vnd.github+json" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # -H "Authorization: token ${{secrets.PAT_REMOTE_TRIGGER}}"
          # repos/Dat-Nguyen-Org/MyProject/dispatches \
          # -f 'event_type=ci' -F "client_payload[unit]=false" -F "client_payload[integration]=true"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_REMOTE_TRIGGER }}
